# Known requirements per distro, please expand if you encounter breakage
known_distros:
  - CentOS
  - Fedora
  - Ubuntu
  - Debian
  - Red Hat Enterprise Linux
  - Arch Linux

debian_deps:
  - build
  - essential
  - libncurses5-dev
  - gawk
  - git
  - subversion
  - libssl-dev
  - gettext
  - unzip
  - zlib1g-dev
  - file
  - python
  - systemtap-sdt-dev

centos_deps:
  - subversion
  - binutils
  - bzip2
  - gcc
  - gcc-c++
  - gawk
  - gettext
  - flex
  - ncurses-devel
  - zlib-devel
  - zlib-static
  - make
  - patch
  - unzip
  - perl-ExtUtils-MakeMaker
  - glibc
  - glibc-devel
  - glibc-static
  - quilt
  - ncurses-libs
  - sed
  - sdcc
  - intltool
  - sharutils
  - bison
  - wget
  - git-core
  - openssl-devel
  - xz
  - systemtap-sdt-devel

ubuntu_deps:
  - build-essential
  - subversion
  - libncurses5-dev
  - zlib1g-dev
  - gawk
  - gcc-multilib
  - flex
  - git-core
  - gettext
  - libssl-dev
  - unzip
  - systemtap-sdt-dev

fedora_deps:
  - subversion
  - binutils
  - bzip2
  - gcc
  - gcc-c++
  - gawk
  - gettext
  - git-core
  - flex
  - ncurses-devel
  - ncurses-compat-libs
  - zlib-devel
  - zlib-static
  - make
  - patch
  - unzip
  - perl-ExtUtils-MakeMaker
  - perl-Thread-Queue
  - glibc
  - glibc-devel
  - glibc-static
  - quilt
  - sed
  - sdcc
  - intltool
  - sharutils
  - bison
  - wget
  - openssl-devel
  - systemtap-sdt-devel

arch_deps:
  - subversion
  - binutils
  - bzip2
  - gcc
  - gcc-libs
  - gawk
  - gettext
  - git
  - flex
  - ncurses
  - zlib
  - automake
  - patch
  - unzip
  - perl
  - glibc
  - quilt
  - sed
  - sdcc
  - intltool
  - sharutils
  - bison
  - wget
  - openssl
  - systemtap

rust_targets:
  - aarch64-unknown-linux-gnu
  - aarch64-unknown-linux-musl
  - i686-unknown-linux-gnu
  - i686-unknown-linux-musl
  - mips-unknown-linux-gnu
  - mips-unknown-linux-musl
  - mipsel-unknown-linux-gnu
  - mipsel-unknown-linux-musl
  - x86_64-unknown-linux-gnu
  - x86_64-unknown-linux-musl
  - arm-unknown-linux-gnueabi
  - arm-unknown-linux-gnueabihf
  - arm-unknown-linux-musleabi
  - arm-unknown-linux-musleabihf
  - armv5te-unknown-linux-gnueabi
  - armv7-unknown-cloudabi-eabihf
  - armv7-unknown-linux-gnueabihf
  - armv7-unknown-linux-musleabihf


