language:
  - c
  - python
  - rust
rust:
  - nightly
cache:
  - ccache
  - pip
  - cargo
install:
  - sudo apt-get install python-pip
  - sudo pip install ansible
  - sudo pip install ansible-lint

sudo: required

env:
  - DEVICE=n600.yml
  - DEVICE=n750.yml
  - DEVICE=virtualbox.yml
  - DEVICE=edgerouterx.yml
  - DEVICE=ar750.yml
  - DEVICE=dir860l.yml
  - DEVICE=wdr3600.yml
  - PROFILE=althea-dev.yml

script:
  - ansible-lint -x ANSIBLE0012,ANSIBLE0013,ANSIBLE0006 *.yml
  - ansible-playbook first-time-setup.yml
  - ansible-playbook -e @profiles/devices/$DEVICE -e @profiles/management/$PROFILE -e ci=True firmware-build.yml
