---
# Upgrades LEDE devices to the newly built firmware
# Use with EXTRAORDINARY CAUTION

- name: Copy over new firmware file
  shell: "scp {{ssh_args}} {{source_dir}}/bin/targets/{{target}}/generic/openwrt-{{target}}-generic-{{device}}-squashfs-sysupgrade.bin root@{{router_ip}}:/tmp/sysupgrade.bin"

- name: Apply the update, please cross your fingers and wait 5 minutes
  shell: "ssh {{ssh_args}} root@{{router_ip}} sysupgrade -v -n /tmp/sysupgrade.bin"
  ignore_errors: true
  async: 0
  poll: 0

- name: Wait for router to come back
  wait_for:
    host: "{{router_ip}}"
    port: 22
    state: started
    delay: 30
    timeout: 600
