source_dir: build
disable_password_login: false
insert_keys: false
keys_to_insert:
  - ""
dropbear_wan_accessible: false
ssh_port: 22
password_auth: 0
default_price: 100
wireless_conf_path: "{{role_path}}/templates/{{conf_to_build}}-wireless.j2"
