---
# Determines if the required dependencies are installed

- name: Install Debian deps
  apt:
    name: "{{debian_deps}}"
    state: present
  when: ansible_distribution == 'Debian'
  become: true

- name: Install Ubuntu deps
  apt:
    name: "{{ubuntu_deps}}"
    state: present
  when: ansible_distribution == 'Ubuntu'
  become: true

- name: Install Fedora deps
  dnf:
    name: "{{fedora_deps}}"
    state: present
  when: ansible_distribution == 'Fedora'
  become: true

- name: Install CentOS/RHEL deps
  yum:
    name: "{{centos_deps}}"
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Red Hat Enterprise Linux'
  become: true

- name: Install Archlinux Deps
  pacman:
    name: "{{arch_deps}}"
    state: present
  when: ansible_distribution == 'Archlinux'
  become: true

- name: Download rust setup script
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y "

- name: Install yarn
  shell: "npm -g install yarn"
