---

- name: "Get internal ip from list"
  shell: "head -n1 internal_ip_list.txt"
  register: internal_ip

- name: "Run setup script"
  shell: "ssh {{ssh_args}} root@192.168.1.1 'internal_ip={{internal_ip.stdout}} ash /etc/setup.ash'"
  register: device_keys

- name: "Print wifi and root pass"
  debug:
    msg: "The password for this router is {{device_keys.stdout_lines[0]}}"

- name: "Display wireguard pubkey"
  debug:
    msg: "Wireguard pubkey {{device_keys.stdout_lines[1]}}"

- name: "Insert router data into storage file"
  blockinfile:
    path: credentials.txt
    block: |
     - wg_pubkey: {{device_keys.stdout_lines[1]}}
       luci_pass: {{device_keys.stdout_lines[0]}}
       internal_ip: {{internal_ip.stdout}}
       mesh_ip: {{device_keys.stdout_lines[2]}}
    insertafter: EOF
    marker: ""
    create: yes

- name: "Delete used ip"
  shell: "sed -i '1d' internal_ip_list.txt"

