---
# Builds the more sensitive and dynamic parts of the firmware root configuration
# for example ssh keys are inserted in this role

- name: Create Dropbear folder
  file:
    path: "{{source_dir}}/files/etc/dropbear/"
    state: directory

- name: Add keys to login
  lineinfile:
    dest: "{{source_dir}}/files/etc/dropbear/authorized_keys"
    line: "{{item}}"
    state: present
    create: yes
  with_items: "{{keys_to_insert}}"
  when: insert_keys

- name: Authorized keys only readable by owner
  file:
    path: "{{source_dir}}/files/etc/dropbear/authorized_keys"
    mode: 0600
  when: insert_keys

- name: Create the UCI config folder
  file:
    path: "{{source_dir}}/files/etc/config/"
    state: directory

- name: Template dropbear config
  template:
    src: "dropbear.j2"
    dest: "{{source_dir}}/files/etc/config/dropbear"

- name: Template firewall config
  template:
    src: "firewall.j2"
    dest: "{{source_dir}}/files/etc/config/firewall"

# Network and wifi stuff is hardware specific, so we keep templates for each
# supported device. it really shouldn't ever change much
# but do remember it's possible
- name: Template network interface configuration
  template:
    src: "{{conf_to_build}}-network.j2"
    dest: "{{source_dir}}/files/etc/config/network"

- debug:
    msg: "{{wireless_conf_path}}"

- name: Template wifi interface configuration
  template:
    src: "{{conf_to_build}}-wireless.j2"
    dest: "{{source_dir}}/files/etc/config/wireless"
  when: wireless_conf_path | is_file


- name: Template the babeld configuration
  template:
    src: "babeld.j2"
    dest: "{{source_dir}}/files/etc/config/babeld"

- name: Write out build details
  template:
    src: "althea-firmware-release.j2"
    dest: "{{source_dir}}/files/etc/althea-firmware-release"


- name: Template bootstrapping script
  template:
    src: "setup.ash.j2"
    dest: "{{source_dir}}/files/etc/setup.ash"

- name: Template package update url
  template:
    src: customfeeds.conf.j2
    dest: "{{source_dir}}/files/etc/opkg/customfeeds.conf"
